package com.pentonix.apache.apiservice;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;

@DynamoDBTable(tableName = "Workflow_Master")
public class WorkflowMaster implements Serializable {
    private static final long serialVersionUID = 1L;
    private String workflowId;//
    private String filename;//
    private Integer nodes;//
    private String workflowName;//
    private String modifiedDate;
    private String creationDate;
    private String modifiedRemark;
    private String tags;//
    private String organizationId;

    @DynamoDBHashKey(attributeName = "workflowId")
    public String getWorkflowId() {
        return workflowId;
    }

    public void setWorkflowId(String workflowId) {
        this.workflowId = workflowId;
    }

    @DynamoDBAttribute
    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @DynamoDBAttribute
    public Integer getNodes() {
        return nodes;
    }

    public void setNodes(Integer nodes) {
        this.nodes = nodes;
    }

    @DynamoDBAttribute
    public String getWorkflowName() {
        return workflowName;
    }

    public void setWorkflowName(String workflowName) {
        this.workflowName = workflowName;
    }

    @DynamoDBAttribute
    public String getModifiedDate() {
        return modifiedDate;
    }

    public void setModifiedDate(String modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @DynamoDBAttribute
    public String getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }
    @DynamoDBAttribute
    public String getModifiedRemark() {
        return modifiedRemark;
    }

    public void setModifiedRemark(String modifiedRemark) {
        this.modifiedRemark = modifiedRemark;
    }

    @DynamoDBAttribute
    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    @DynamoDBAttribute
	public String getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(String organizationId) {
		this.organizationId = organizationId;
	}
}
